# MySQL (Disabled for deployment)
# spring.datasource.url=jdbc:mysql://localhost/studbase
# spring.datasource.username=root
# spring.datasource.password=root

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Render Port
server.port=${PORT:8080}